# Docker Compose file for the URLshortening-distributed-system

version: "3.8"

services:
  # Server service
  server:
    container_name: server-container
    build:
      context: ./server # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile # Name of the Dockerfile
    ports:
      - "8000:8000" # Mapping port 8000 of the host to port 8000 of the container
    env_file:
      - ./server/.env
  # Client service
  client:
    container_name: client-container
    build:
      context: ./client # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile # Name of the Dockerfile
    ports:
      - "3000:3000" # Mapping port 3000 of the host to port 3000 of the container
    depends_on:
      - server # Ensure server service is started before the client
